# Generated by Django 5.0.14 on 2026-08-26 10:02

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0002_historicalratecontract_ratecontract_and_more'),
        ('purchase', '0005_historicalpurchaseorderline_qty_already_billed_and_more'),
        ('stores', '0002_historicalstockissue_historicalstocktransfer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTransportTrip',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('trip_number', models.CharField(blank=True, db_index=True, max_length=40)),
                ('trip_date', models.DateField(default=django.utils.timezone.localdate)),
                ('vehicle_number', models.CharField(max_length=30)),
                ('driver_name', models.CharField(blank=True, max_length=255)),
                ('driver_phone', models.CharField(blank=True, max_length=15)),
                ('from_location', models.CharField(help_text='Free text, or a site name for factory dispatches.', max_length=255)),
                ('element_description', models.CharField(blank=True, help_text='Free description for precast element deliveries (no PO/GRN link).', max_length=255)),
                ('freight_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('billable_to', models.CharField(choices=[('company', 'Company'), ('vendor', 'Vendor'), ('client', 'Client')], default='company', max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('pod_photo', models.TextField(blank=True, help_text='Proof of delivery.', max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('linked_grn', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stores.grn')),
                ('linked_po', models.ForeignKey(blank=True, db_constraint=False, help_text='For inward material trips.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchase.purchaseorder')),
                ('to_site', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.site')),
                ('transporter', models.ForeignKey(blank=True, db_constraint=False, help_text='Vendor tagged with the Transport category.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.vendor')),
            ],
            options={
                'verbose_name': 'historical transport trip',
                'verbose_name_plural': 'historical transport trips',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TransportTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip_number', models.CharField(blank=True, max_length=40, unique=True)),
                ('trip_date', models.DateField(default=django.utils.timezone.localdate)),
                ('vehicle_number', models.CharField(max_length=30)),
                ('driver_name', models.CharField(blank=True, max_length=255)),
                ('driver_phone', models.CharField(blank=True, max_length=15)),
                ('from_location', models.CharField(help_text='Free text, or a site name for factory dispatches.', max_length=255)),
                ('element_description', models.CharField(blank=True, help_text='Free description for precast element deliveries (no PO/GRN link).', max_length=255)),
                ('freight_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('billable_to', models.CharField(choices=[('company', 'Company'), ('vendor', 'Vendor'), ('client', 'Client')], default='company', max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('pod_photo', models.ImageField(blank=True, help_text='Proof of delivery.', null=True, upload_to='trip_pods/%Y/%m/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('linked_grn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='stores.grn')),
                ('linked_po', models.ForeignKey(blank=True, help_text='For inward material trips.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='purchase.purchaseorder')),
                ('to_site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbound_trips', to='masters.site')),
                ('transporter', models.ForeignKey(help_text='Vendor tagged with the Transport category.', on_delete=django.db.models.deletion.PROTECT, related_name='transport_trips', to='masters.vendor')),
            ],
            options={
                'ordering': ['-trip_date', '-created_at'],
            },
        ),
    ]
