# Generated by Django 5.0.14 on 2026-08-26 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('logistics', '0001_initial'),
        ('purchase', '0005_historicalpurchaseorderline_qty_already_billed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbill',
            name='transport_trips',
            field=models.ManyToManyField(blank=True, help_text='For transporter freight bills, in place of a PO — uses a 2-way match (trip freight vs bill total).', related_name='bills', to='logistics.transporttrip'),
        ),
        migrations.AlterField(
            model_name='historicalvendorbill',
            name='po',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Leave blank for a freight bill linked to transport trips instead.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchase.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='po',
            field=models.ForeignKey(blank=True, help_text='Leave blank for a freight bill linked to transport trips instead.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='purchase.purchaseorder'),
        ),
    ]
