# Generated by Django 5.0.14 on 2026-10-07 08:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalindentline',
            name='present_stock',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.000'), max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='historicalindentline',
            name='required_by_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indentline',
            name='present_stock',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.000'), max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='indentline',
            name='required_by_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
