# Generated by Django 5.0.14 on 2026-08-26 10:07

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0002_historicalratecontract_ratecontract_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMachine',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('code', models.CharField(blank=True, db_index=True, help_text='Auto-generated, e.g. MC-0001', max_length=20)),
                ('name', models.CharField(help_text='e.g. "Batching Plant 30cum", "Hydra Crane 14T"', max_length=255)),
                ('category', models.CharField(choices=[('batching', 'Batching'), ('cranes', 'Cranes'), ('moulds', 'Moulds'), ('vehicles', 'Vehicles'), ('tools', 'Tools'), ('other', 'Other')], max_length=20)),
                ('ownership', models.CharField(choices=[('owned', 'Owned'), ('hired', 'Hired')], max_length=10)),
                ('hire_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rate_unit', models.CharField(blank=True, choices=[('per_hour', 'Per hour'), ('per_day', 'Per day'), ('per_month', 'Per month')], max_length=10)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('under_maintenance', 'Under maintenance'), ('idle', 'Idle'), ('disposed', 'Disposed')], default='active', max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hire_vendor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.vendor')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical machine',
                'verbose_name_plural': 'historical machines',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, help_text='Auto-generated, e.g. MC-0001', max_length=20, unique=True)),
                ('name', models.CharField(help_text='e.g. "Batching Plant 30cum", "Hydra Crane 14T"', max_length=255)),
                ('category', models.CharField(choices=[('batching', 'Batching'), ('cranes', 'Cranes'), ('moulds', 'Moulds'), ('vehicles', 'Vehicles'), ('tools', 'Tools'), ('other', 'Other')], max_length=20)),
                ('ownership', models.CharField(choices=[('owned', 'Owned'), ('hired', 'Hired')], max_length=10)),
                ('hire_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rate_unit', models.CharField(blank=True, choices=[('per_hour', 'Per hour'), ('per_day', 'Per day'), ('per_month', 'Per month')], max_length=10)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('under_maintenance', 'Under maintenance'), ('idle', 'Idle'), ('disposed', 'Disposed')], default='active', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hire_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hired_machines', to='masters.vendor')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalMachineDeployment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, help_text='Leave blank — still at this site.', null=True)),
                ('remarks', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.site')),
                ('machine', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='assets.machine')),
            ],
            options={
                'verbose_name': 'historical machine deployment',
                'verbose_name_plural': 'historical machine deployments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MachineDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, help_text='Leave blank — still at this site.', null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='assets.machine')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machine_deployments', to='masters.site')),
            ],
            options={
                'ordering': ['-from_date'],
            },
        ),
        migrations.CreateModel(
            name='MachineLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('log_date', models.DateField(default=django.utils.timezone.localdate)),
                ('hours_run', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fuel_litres', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('operator_name', models.CharField(blank=True, max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='assets.machine')),
                ('site', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='machine_logs', to='masters.site')),
            ],
            options={
                'ordering': ['-log_date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('every_n_days', models.PositiveIntegerField(blank=True, null=True)),
                ('every_n_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('last_done_date', models.DateField(blank=True, null=True)),
                ('last_done_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='assets.machine')),
            ],
            options={
                'ordering': ['machine'],
            },
        ),
        migrations.AddConstraint(
            model_name='machinedeployment',
            constraint=models.UniqueConstraint(condition=models.Q(('to_date__isnull', True)), fields=('machine',), name='unique_open_deployment_per_machine'),
        ),
    ]
