# Generated by Django 5.0.14 on 2026-08-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_alter_poapprovalaction_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvalrule',
            options={'ordering': ['doc_type', 'min_amount']},
        ),
        migrations.AddField(
            model_name='approvalrule',
            name='doc_type',
            field=models.CharField(choices=[('po', 'Purchase Order'), ('indent', 'Indent'), ('bill', 'Vendor Bill')], default='po', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalapprovalrule',
            name='doc_type',
            field=models.CharField(choices=[('po', 'Purchase Order'), ('indent', 'Indent'), ('bill', 'Vendor Bill')], default='po', max_length=10),
        ),
    ]
