# Generated by Django 5.0.14 on 2026-08-26 09:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indents', '0001_initial'),
        ('purchase', '0003_alter_approvalrule_options_approvalrule_doc_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='delivery_complete',
            field=models.BooleanField(default=False, editable=False, help_text='All lines fully received per GRNs; set by stores app, not by PO status alone.'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='source_indent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indents.indent'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseorderline',
            name='indent_line',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indents.indentline'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseorderline',
            name='indent_qty_recorded',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, help_text="How much of this line's quantity has already been rolled up onto the indent line.", max_digits=12),
        ),
        migrations.AddField(
            model_name='historicalpurchaseorderline',
            name='qty_received',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, help_text='Cumulative accepted quantity across GRNs (stores app).', max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_complete',
            field=models.BooleanField(default=False, editable=False, help_text='All lines fully received per GRNs; set by stores app, not by PO status alone.'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='source_indent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='indents.indent'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='indent_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_lines', to='indents.indentline'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='indent_qty_recorded',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, help_text="How much of this line's quantity has already been rolled up onto the indent line.", max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='qty_received',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, help_text='Cumulative accepted quantity across GRNs (stores app).', max_digits=12),
        ),
    ]
