# Generated by Django 5.0.14 on 2026-08-26 09:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_historicalpurchaseorder_delivery_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchaseorderline',
            name='qty_already_billed',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, help_text='Cumulative billed quantity, updated when a bill is approved for payment (billing app).', max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='qty_already_billed',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, help_text='Cumulative billed quantity, updated when a bill is approved for payment (billing app).', max_digits=12),
        ),
    ]
