from collections import defaultdict
from decimal import Decimal

from django.contrib.auth.models import User
from django.core.management.base import BaseCommand

from accounts_stub.notifications import notify
from indents.models import Indent, IndentLine
from stores.models import SiteItemSetting, StockBalance

AUTO_INDENT_MARKER = "Auto-generated by check_min_stock"


class Command(BaseCommand):
    help = (
        "Nightly check: flags items below their per-site minimum stock level "
        "(SiteItemSetting.min_stock_qty) and drafts (never auto-submits) an "
        "indent per site for the shortfall, notifying that site's members. "
        "Items already sitting on an unresolved auto-generated draft indent "
        "are not re-flagged."
    )

    def handle(self, *args, **options):
        flagged_by_site = defaultdict(list)
        for setting in SiteItemSetting.objects.filter(min_stock_qty__gt=0).select_related("site", "item"):
            balance = StockBalance.objects.filter(site=setting.site, item=setting.item).first()
            current = balance.quantity if balance else Decimal("0")
            if current < setting.min_stock_qty:
                flagged_by_site[setting.site].append((setting.item, setting.min_stock_qty - current))

        indents_created = 0
        for site, items in flagged_by_site.items():
            existing_draft_items = set()
            for indent in Indent.objects.filter(site=site, status=Indent.Status.DRAFT, remarks__icontains=AUTO_INDENT_MARKER):
                existing_draft_items.update(indent.lines.values_list("item_id", flat=True))

            new_items = [(item, qty) for item, qty in items if item.pk not in existing_draft_items]
            if not new_items:
                continue

            system_user = (
                User.objects.filter(profile__site=site, groups__name="Site Member", is_active=True).first()
                or User.objects.filter(is_superuser=True).first()
            )
            if not system_user:
                self.stderr.write(self.style.WARNING(f"No user to attribute a draft indent to for {site.code}; skipping."))
                continue

            indent = Indent.objects.create(
                site=site, raised_by=system_user,
                remarks=f"{AUTO_INDENT_MARKER}: {len(new_items)} item(s) below minimum stock level.",
                created_by=system_user,
            )
            for item, qty in new_items:
                IndentLine.objects.create(
                    indent=indent, item=item, quantity=qty, purpose="Auto-replenishment (below min stock)",
                    created_by=system_user,
                )
            indents_created += 1

            for member in User.objects.filter(profile__site=site, groups__name="Site Member", is_active=True):
                notify(
                    member, f"Low stock at {site.code}",
                    f"{len(new_items)} item(s) below minimum stock level. "
                    f"Draft indent {indent.indent_number} created for review — it will not be submitted automatically.",
                )

        self.stdout.write(self.style.SUCCESS(f"check_min_stock: {indents_created} draft indent(s) created."))
